### ISSUE TITLE
Feb2023 7j: Is the {null set} a subset of the P(A)? Should be True?

### ISSUE THREAD

**Issue by gradyf** [ethanbell13/NYUBridgeExamPrepAnswerKeys#7]
<img width="693" alt="image" src="https://github.com/ethanbell13/NYUBridgeExamPrepAnswerKeys/assets/12043601/06a4369a-da73-467a-8f6c-14b9b87ab8db">

I believe J should be true given that everything on the left ( {nullset} ) is a en element of the right (P(A)). Given the discord discussion, this would make the statement True.

**Comment by ethanbell13** [comment]
7j has been updated to true. Thanks for the help.
