### ISSUE TITLE
Incorrect solution Question 2

### ISSUE THREAD

**Issue by ezappala** [ethanbell13/NYUBridgeExamPrepAnswerKeys#9]
See: [Exam_2/Answer_Keys/Sep2021_Exam2_Answer_Key/q1to4.cpp](https://github.com/ethanbell13/NYUBridgeExamPrepAnswerKeys/blob/main/Exam_2/Answer_Keys/Sep2021_Exam2_Answer_Key/q1to4.cpp)

Question 2: 
In how many permutations of the digits 1-9, there are only even digits in the first 3 places?

Provided ans: 
First we must find how many permuations there are for 3 even digits, which is P(5,3)
    We then find the perumations for the  remaining 6 digits.
    Answer = P(5,3)*6! = 5 * 4 * 3 * 6!
    
However there are only 4 even digits between 1 and 9, (2, 4, 6, 8)

**Comment by ethanbell13** [comment]
Thanks for catching that. The answer key has been corrected.
